[workspace]
members = [
    "proxy_types",
    "proxy",
]

# [patch."ssh://git@github.com/fiberplane/providers.git"]
# fp-provider-runtime = { path = "../providers/runtimes/fp-provider-runtime/" }

# [patch."ssh://git@github.com/fiberplane/tokio-tungstenite-reconnect.git"]
# tokio-tungstenite-reconnect = { path = "../tokio-tungstenite-reconnect" }

# [patch.'ssh://git@github.com/fiberplane/fiberplane-rs.git']
# base64uuid = { path = "../fiberplane-rs/base64uuid" }
# fiberplane = { path = "../fiberplane-rs/fiberplane" }
# fp-provider-runtime = { path = "../fiberplane-rs/fp-provider-protocol/fp-provider-runtime" }
# fp-api-client = { path = "../fiberplane-rs/fp-api-client" }
# fp-templates = { path = "../fiberplane-rs/fp-templates" }
