[workspace]
members = [
    "proxy_types",
    "proxy",
]

# [patch."ssh://git@github.com/fiberplane/providers.git"]
# fp-provider-runtime = { path = "../providers/runtimes/fp-provider-runtime/" }

# [patch."ssh://git@github.com/fiberplane/tokio-tungstenite-reconnect.git"]
# tokio-tungstenite-reconnect = { path = "../tokio-tungstenite-reconnect" }
