[package]
name = "proxy"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.4"
fp-plugins = { git = "ssh://git@github.com/fiberplane/plugins-rs.git", branch = "main" }
# fp-plugins = { path = "../../plugins-rs/runtime"  }
futures = "0.3.17"
hyper = { version = "0.14.12", features = ["full"] }
hyper-tungstenite = "0.4.0"
rmp-serde = "0.15.5"
routerify = "2.2.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.10.1", features = ["full"] }
tokio-tungstenite = "0.15.0"
url = "2.2.2"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
wasmer = {version = "2.0.0", features = ["singlepass"] }
