---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: proxy:latest
          imagePullPolicy: Always
          env:
            - name: RUST_LOG
              value: proxy=trace
            - name: AUTH_TOKEN
              value: ${AUTH_TOKEN}
            - name: LISTEN_ADDRESS
              value: 0.0.0.0:3002
            - name: FIBERPLANE_ENDPOINT
              value: ${FIBERPLANE_ENDPOINT-wss://fiberplane.com/api/ws}
          ports:
            - containerPort: 3002
