---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: "${IMAGE-proxy}:${TAG-latest}"
          imagePullPolicy: Always
          env:
            - name: RUST_LOG
              valueFrom:
                configMapKeyRef:
                  name: proxy-config
                  key: rust_log
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: proxy-secrets
                  key: token
            - name: LISTEN_ADDRESS
              value: 0.0.0.0:3002
            - name: API_BASE
              valueFrom:
                configMapKeyRef:
                  name: fiberplane-config
                  key: base_url
            - name: DATA_SOURCES_PATH
              value: /app/config/data_sources.yaml
          ports:
            - containerPort: 3002
          volumeMounts:
            - mountPath: /app/config/data_sources.yaml
              name: data-sources
              subPath: data_sources.yaml
      volumes:
        - name: data-sources
          secret:
            secretName: proxy-secrets
            items:
              - key: data_sources.yaml
                path: data_sources.yaml
