---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fpd
  labels:
    app: fpd
spec:
  selector:
    matchLabels:
      app: fpd
  template:
    metadata:
      labels:
        app: fpd
    spec:
      containers:
        - name: fpd
          image: fpd:latest
          imagePullPolicy: Always
          env:
            - name: RUST_LOG
              value: ${RUST_LOG-fpd=trace}
            - name: TOKEN
              value: ${TOKEN}
            - name: LISTEN_ADDRESS
              value: 0.0.0.0:3002
            - name: API_BASE
              value: ${API_BASE-https://studio.fiberplane.com/}
            - name: DATA_SOURCES_PATH
              value: /app/config/data_sources.yaml
            - name: WASM_DIR
              value: /app/providers
          ports:
            - containerPort: 3002
          volumeMounts:
            - mountPath: /app/config/data_sources.yaml
              name: data-sources
              subPath: data_sources.yaml
      volumes:
        - name: data-sources
          configMap:
            name: fpd
            defaultMode: 420
            items:
              - key: data_sources.yaml
                path: data_sources.yaml
