---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: proxy:latest
          imagePullPolicy: Always
          env:
            - name: RUST_LOG
              value: ${RUST_LOG-proxy=trace}
            - name: TOKEN
              value: ${TOKEN}
            - name: LISTEN_ADDRESS
              value: 0.0.0.0:3002
            - name: API_BASE
              value: ${API_BASE-https://studio.fiberplane.com/}
            - name: DATA_SOURCES_PATH
              value: /app/config/data_sources.yaml
          ports:
            - containerPort: 3002
          volumeMounts:
            - mountPath: /app/config/data_sources.yaml
              name: data-sources
              subPath: data_sources.yaml
      volumes:
        - name: data-sources
          configMap:
            name: proxy
            defaultMode: 420
            items:
              - key: data_sources.yaml
                path: data_sources.yaml
