# This will deploy the Kubernetes manifests to a cluster, containing references
# to our release Docker images (ie. tags that use versions).
---
name: Deploy release images to cluster

on:
  workflow_call:
    inputs:
      environment:
        description: The fiberplane environment
        required: true
        type: string
      version:
        description: Version that needs to be deployed
        required: true
        type: string
      trigger:
        description: The source that triggered the deploy, either manual or auto
        default: "auto"
        type: string
    secrets:
      DEPLOY_STARTED_SLACK_WEBHOOK_URL:
        required: true
      DEPLOY_FINISHED_SLACK_WEBHOOK_URL:
        required: true
      DEPLOY_FAILED_SLACK_WEBHOOK_URL:
        required: true
      FIBERPLANE_TOKEN:
        required: true
      FIBERPLANE_DEMO_TOKEN:
        required: true
      FIBERPLANE_DEV_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: "cluster-${{ inputs.environment }}"
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::901443922744:role/github_actions

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v1

      - id: vars
        name: Export variables
        env:
          SERVICE: fpd
        run: |
          if [ "${{ inputs.environment }}" == "production" ]; then
            echo "ingress_root_domain=studio.fiberplane.com" >> $GITHUB_OUTPUT
          else
            echo "::set-output name=ingress_root_domain::${{ inputs.environment }}.fiberplane.io"
          fi
          short_sha=$(git rev-parse --short "${{ github.event.pull_request.head.sha || github.sha }}")
          echo "SHORT_SHA=${short_sha}" >> $GITHUB_ENV
          echo "SERVICE=${SERVICE}" >> $GITHUB_ENV
          echo "IMAGE=${{ steps.ecr.outputs.registry }}/${SERVICE}" >> $GITHUB_ENV
          # Dev releases do not have the 'release-' prefix to the image tag
          if [ "${{ inputs.environment }}" == "dev"]; then
            echo "TAG=${{ inputs.version }}" >> $GITHUB_ENV
          else
            echo "TAG=release-${{ inputs.version }}" >> $GITHUB_ENV
          fi

      - name: Send "deploy started" to Slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "environment": "${{ inputs.environment }}",
              "component": "${{ env.SERVICE }}",
              "trigger": "manual",
              "version": "${{ inputs.version }}",
              "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.DEPLOY_STARTED_SLACK_WEBHOOK_URL }}

      - name: Downgrade kubectl to version v1.23.6
        run: |
          curl -LO https://dl.k8s.io/release/v1.23.6/bin/linux/amd64/kubectl
          chmod u+x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

      - name: Verify image exists
        run: |
          if ! docker pull "$IMAGE:$TAG" ; then
            echo "::error::Image was not found, please wait until it is finished uploading"
            exit 1
          fi

      - name: Template Kubernetes files
        env:
          VERSION: "${{ inputs.version }}"
          FP_ENVIRONMENT: "${{ inputs.environment }}"
          FP_INGRESS_ROOT_DOMAIN: ${{ steps.vars.outputs.ingress_root_domain }}
        run: scripts/template_all.sh "deployment/*.template.yaml" > result.yaml

      - name: Create kubeconfig
        env:
          FP_ENVIRONMENT: "${{ inputs.environment }}"
        run: aws eks update-kubeconfig --name "${FP_ENVIRONMENT}-cluster"

      - name: Kubectl version
        run: kubectl version --client=true

      - name: Apply kubernetes resources
        run: kubectl apply -f result.yaml

      - name: Wait for Kubernetes deployment
        run: kubectl rollout status deployment fpd

      - name: Send "deploy finished" to Slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "environment": "${{ inputs.environment }}",
              "component": "${{ env.SERVICE }}",
              "trigger": "${{ inputs.trigger }}",
              "version": "${{ inputs.version }}",
              "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.DEPLOY_FINISHED_SLACK_WEBHOOK_URL }}

      - name: Send "deploy failed" to Slack
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "environment": "${{ inputs.environment }}",
              "component": "${{ env.SERVICE }}",
              "trigger": "${{ inputs.trigger }}",
              "version": "${{ inputs.version }}",
              "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.DEPLOY_FAILED_SLACK_WEBHOOK_URL }}

  post-event:
    name: Post deployment to all Fiberplane environments
    uses: fiberplane/fpd/.github/workflows/post_event.yml@main
    needs: deploy
    with:
      service: fpd
      trigger: ${{ inputs.trigger }}
      environment: ${{ inputs.environment }}
      version: ${{ inputs.version }}
    secrets:
      FIBERPLANE_TOKEN: ${{ secrets.FIBERPLANE_TOKEN }}
      FIBERPLANE_DEMO_TOKEN: ${{ secrets.FIBERPLANE_DEMO_TOKEN }}
      FIBERPLANE_DEV_TOKEN: ${{ secrets.FIBERPLANE_DEV_TOKEN }}
